spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

logging:
  level:
    root: WARN
    com.example.demo: INFO
    org.springframework.web: WARN
